name: Feature
description: Functional development work
title: "<module>: <feature description>"
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria

  - type: textarea
    id: related_adr
    attributes:
      label: Related ADR (if any)
      description: Link to ADR issue
